# Matteblack color scheme for Wezterm
# Based on matteblack.nvim by Taha Nejad
# vim:filetype=toml

[metadata]
name = "matteblack"

[colors]
background = "#0D0D0D"
foreground = "#EAEAEA"
cursor_bg = "#121212"
cursor_fg = "#F59E0B"
cursor_border = "#F59E0B"
selection_bg = "#262626"
selection_fg = "#FFFFFF"
scrollbar_thumb = "#333333"

# Tab bar
tab_bar_bg = "#0D0D0D"
tab_bar_active_tab_fg = "#EAEAEA"
tab_bar_active_tab_bg = "#121212"
tab_bar_inactive_tab_fg = "#8A8A8D"
tab_bar_inactive_tab_bg = "#0D0D0D"

# ANSI colors (must be array!)
ansi = [
  "#333333",  -- black
  "#B91C1C",  -- red
  "#059669",  -- green
  "#FBBF24",  -- yellow
  "#3B82F6",  -- blue
  "#8D20B2",  -- magenta
  "#1EA7A0",  -- cyan
  "#EAEAEA",  -- white
]

# Bright colors (must be array!)
brights = [
  "#8A8A8D",  -- bright black
  "#DC2626",  -- bright red
  "#10B981",  -- bright green
  "#EFBF04",  -- bright yellow
  "#3B82F6",  -- bright blue
  "#B027DE",  -- bright magenta
  "#1EA7A0",  -- bright cyan
  "#FFFFFF",  -- bright white
]
